mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath*:mappers/*.xml
spring.sql.init.mode: always
spring:
  h2:
    console:
      enabled: true
      path: /h2-console